
const product = [
    {
      id: 1,
      name: "Allen Solly",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Men",
      subCategory: "Men",
      createdAt: " 22-10-2021",
      productImage: "../assets/m1.jpg",
      tag: [],
    },
    {
      id: 2,
      name: "HRX",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Women",
      subCategory: "Women",
      createdAt: " 22-10-2021",
      productImage: "../assets/w1.jpg",
      tag: [],
    },
    {
      id: 3,
      name: "Boy-Shirt",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Kids",
      subCategory: "Kids",
      createdAt: " 22-10-2021",
      productImage: "../assets/k1.jpg",
      tag: [],
    },
    {
      id: 4,
      name: "Tresemme",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Beauty",
      subCategory: "Beauty",
      createdAt: " 22-10-2021",
      productImage: "../assets/b1.jpg",
      tag: [],
    },
    {
      id: 5,
      name: "Fab-Lamp",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Home-Living",
      subCategory: "Home-Living",
      createdAt: " 22-10-2021",
      productImage: "../assets/h1.jpg",
      tag: [],
    },
    {
      id: 6,
      name: "FaceMask",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Other",
      subCategory: "Other",
      createdAt: " 22-10-2021",
      productImage: "../assets/o2.jpg",
      tag: [],
    },
    {
      id: 7,
      name: "T-Shirt",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Men",
      subCategory: "Men",
      createdAt: " 22-10-2021",
      productImage: "../assets/m2.jpg",
      tag: [],
    },
    {
      id: 8,
      name: "Nayo",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Women",
      subCategory: "Women",
      createdAt: " 22-10-2021",
      productImage: "../assets/w2.jpg",
      tag: [],
    },
    {
      id: 9,
      name: "Jeans",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Kids",
      subCategory: "Kids",
      createdAt: " 22-10-2021",
      productImage: "../assets/k2.jpg",
      tag: [],
    },
    {
      id: 10,
      name: "",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Beauty",
      subCategory: "Beauty",
      createdAt: " 22-10-2021",
      productImage: "../assets/b2.jpg",
      tag: [],
    },
    {
      id: 11,
      name: "Cushion",
      description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle`,
      price: 150,
      category: "Home-Living",
      subCategory: "Home-Living",
      createdAt: " 22-10-2021",
      productImage: "../assets/h2.jpg",
      tag: [],
    },
    
]

export default product;